### ISSUE TITLE
ActionView::TemplateError (undefined method `edit_project_board_path' for #<ActionView::Base:0x652c020>) on line #27 of vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:

### ISSUE THREAD

**Issue by ChrisMcKee** [cforce/redmine_boards_watchers#1]
- Redmine 1.3.0.stable 

ActionView::TemplateError (undefined method `edit_project_board_path' for #ActionView::Base:0x652c020) on line #27 of vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:
24:     <% end %>
25: <%# VVK Lines added by boards watchers plugin - end %>
26:     <% if User.current.allowed_to?(:manage_boards, @project) %>
27:       <%= link_to l(:button_edit), edit_project_board_path(@project, board), :class => 'icon icon-edit' %>
28:       <%= link_to l(:button_delete), project_board_path(@project, board), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
29:     <% end %>
30:     </td>

```
vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:27
vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:10
app/views/common/_tabs.html.erb:24
app/views/common/_tabs.html.erb:23:in `each'
app/views/common/_tabs.html.erb:23
app/helpers/application_helper.rb:222:in `render_tabs'
app/views/projects/settings.html.erb:3
config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'
```

Rendering D:/BitNamiRedmineStack/apps/redmine/public/500.html (500 Internal Server Error)

---

I attempted to copy the VLK bits into the view from the redmine install and had the same issue

Rendering template within layouts/base
Rendering projects/settings

ActionView::TemplateError (undefined method `edit_project_board_path' for #ActionView::Base:0x6491f10) on line #27 of vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:
24:     <% end %>
25: <%# VVK Lines added by boards watchers plugin - end %>
26:     <% if User.current.allowed_to?(:manage_boards, @project) %>
27:       <%= link_to l(:button_edit), edit_project_board_path(@project, board), :class => 'icon icon-edit' %>
28:       <%= link_to l(:button_delete), project_board_path(@project, board), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
29:     <% end %>
30:     </td>

```
vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:27
vendor/plugins/redmine_boards_watchers/app/views/projects/settings/_boards.html.erb:10
app/views/common/_tabs.html.erb:24
app/views/common/_tabs.html.erb:23:in `each'
app/views/common/_tabs.html.erb:23
app/helpers/application_helper.rb:222:in `render_tabs'
app/views/projects/settings.html.erb:3
config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'
```

Rendering D:/BitNamiRedmineStack/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by cforce** [comment]
Unfortunately, thi is the common problem when replacing views files in the plugin - you have to come up with the version for every view that is changed in Redmine itself. For those of you who can do file editing i would recommend to open view files from latest plugin and look for #VVK lines. Then copy file from Redmine view folder to plugin view folder and add lines between # VVK comments. This way you will get error free version. For all the others i believe soon i will be able to come up with decision that will allow to have several versions of the views for the single plugin. Please stay tuned.

**Comment by ChrisMcKee** [comment]
I tried that originally (after seeing it in the forums); the only difference between the redmine view in my install and the plugin view is the VLK lines, so when I pasted it in it still throws the same error. What version was the plugin written against?

**Comment by cforce** [comment]
1.2
